import { Skill } from "./skill";

export const imageBaseUrl = "assets/";

export const imagesToPreload = [
    "iam/wrike-items.jpg",
    "iam/meetup.jpg",
    "iam/gdg.jpg",
    "iam/delphi-old-school-kringe.png",
    "certs/olymp0.jpg",
    "certs/olymp1.jpeg",
    "certs/stepik.png",
    "certs/coursera.png",
];

export const skillsByCategoryMap: Record<string, Skill[]> =  {
    "Языки": [
        new Skill("C"),
        new Skill("Go"),
        new Skill("Rust"),
        new Skill("Python"),
        new Skill("JavaScript"),
        new Skill("TypeScript"),
        new Skill("Node.js"),
        new Skill("Dart"),
        new Skill("C++"),
        new Skill("Assembler x86"),
        new Skill("PHP"),
        new Skill("SQL"),
        new Skill("HTML"),
        new Skill("CSS"),
        new Skill("Bash"),
    ],
    "База разработки": [
        new Skill("Алгоритмы и структуры данных"),
        new Skill("Многопоточность"),
        new Skill("Операционные системы"),
        new Skill("Базы данных"),
        new Skill("ООП"),
        new Skill("SOLID"),
        new Skill("DDD"),
        new Skill("Чистая архитектура"),
        new Skill("Функциональное программирование"),
    ],
    "Инструменты разработки": [
        new Skill("Git"),
        new Skill("Gitlab"),
        new Skill("Github"),
        new Skill("CI/CD"),
        new Skill("Linux"),
        new Skill("Docker"),
        new Skill("Docker Compose"),
        new Skill("REST API"),
        new Skill("GraphQL"),
        new Skill("RPC"),
        new Skill("GRPC"),
        new Skill("SQLite"),
        new Skill("MySQL"),
        new Skill("PostgreSQL"),
        new Skill("MongoDB"),
    ],
    "Фреймворки & SDK": [
        new Skill("Angular"),
        new Skill("React"),
        new Skill("Vue"),
        new Skill("Redux"),
        new Skill("Rx"),
        new Skill("SCSS"),
        new Skill("Less"),
        new Skill("Bottle"),
        new Skill("Flask"),
        new Skill("Express.js"),
        new Skill("Flutter"),
        new Skill("Electron.js"),
    ],
    "Soft-скилы": [
        new Skill("English B1"),
        new Skill("Agile"),
        new Skill("Kanban"),
        new Skill("Scrum"),
        new Skill("Управление проектами"),
        new Skill("Teamlead"),
    ],
    "Приложения": [
        new Skill("VSCode"),
        new Skill("AI инструменты для разработки"),
        new Skill("Trello"),
        new Skill("Wrike"),
        new Skill("Asana"),
        new Skill("Jira"),
    ],
};