import { Skill } from "./models/skill";
import { SkillCategory } from "./models/skill-category";

export const imageBaseUrl = "assets/";

export const imagesToPreload = [
    "iam/wrike-items.webp",
    "iam/meetup.jpg",
    "iam/gdg.webp",
    "iam/delphi-old-school-kringe.webp",
    "certs/olymp0.webp",
    "certs/olymp1.webp",
    "certs/stepik.png",
    "certs/coursera.webp",
];

export const skillsByCategoryMap = new Map([
    [SkillCategory.langs, [
        new Skill("C"),
        new Skill("Go"),
        new Skill("Rust"),
        new Skill("Python"),
        new Skill("JavaScript"),
        new Skill("TypeScript"),
        new Skill("Node.js"),
        new Skill("Dart"),
        new Skill("C++"),
        new Skill("Assembler x86"),
        new Skill("PHP"),
        new Skill("SQL"),
        new Skill("HTML"),
        new Skill("CSS"),
        new Skill("Bash"),
    ]],
    [SkillCategory.base, [
        new Skill("Алгоритмы и структуры данных"),
        new Skill("Многопоточность"),
        new Skill("Операционные системы"),
        new Skill("Базы данных"),
        new Skill("ООП"),
        new Skill("SOLID"),
        new Skill("TDD"),
        new Skill("DDD"),
        new Skill("Чистая архитектура"),
        new Skill("Микрофронтенды"),
        new Skill("Функциональное программирование"),
    ]],
    [SkillCategory.tools, [
        new Skill("Git"),
        new Skill("Gitlab"),
        new Skill("Github"),
        new Skill("CI/CD"),
        new Skill("Linux"),
        new Skill("Docker"),
        new Skill("Docker Compose"),
        new Skill("REST API"),
        new Skill("GraphQL"),
        new Skill("RPC"),
        new Skill("GRPC"),
        new Skill("SQLite"),
        new Skill("MySQL"),
        new Skill("PostgreSQL"),
        new Skill("MongoDB"),
        new Skill("Firebase"),
    ]],
    [SkillCategory.libs, [
        new Skill("Angular"),
        new Skill("React"),
        new Skill("Vue"),
        new Skill("jQuery"),
        new Skill("Webpack"),
        new Skill("Rspack"),
        new Skill("WASM"),
        new Skill("SCSS"),
        new Skill("Less"),
        new Skill("Bottle"),
        new Skill("Flask"),
        new Skill("Gin"),
        new Skill("Sqlx"),
        new Skill("Express.js"),
        new Skill("Electron.js"),
        new Skill("Flutter"),
        new Skill("Rx"),
        new Skill("Redux"),
        new Skill("Provider"),
        new Skill("Bloc"),
        new Skill("Riverpod"),
        new Skill("Drift"),
        new Skill("Leptos"),
        new Skill("Tokio"),
        new Skill("Rayon"),
        new Skill("Crossbeam"),
    ]],
    [SkillCategory.soft, [
        new Skill("English B1"),
        new Skill("Agile"),
        new Skill("Kanban"),
        new Skill("Scrum"),
        new Skill("Управление проектами"),
        new Skill("Teamlead"),
    ]],
    [SkillCategory.apps, [
        new Skill("VSCode"),
        new Skill("AI инструменты для разработки"),
        new Skill("Trello"),
        new Skill("Wrike"),
        new Skill("Asana"),
        new Skill("Jira"),
    ]],
]);