name: Deploy landing to geooooo.github.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Rust
        run: rustup update stable && rustup default stable

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25.3.0
          
      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy to geooooo.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: geooooo/geooooo
          publish_branch: public
          publish_dir: ./dist
          force_orphan: true
          cname: yury-kornienko.pro
